### ISSUE TITLE
Update density/volume of material point

### ISSUE THREAD

**Issue by kks32** [cb-geo/mpm#176]
* Update the density of material point based on new volume, calculated using the volumetric strain of the cell.

**Comment by kks32** [comment]
Map Internal force in Particle class has the following calculation for volume:

`this->mass_(phase) / material_->property("density")` -  should use volume!

**Comment by cbgeo** [comment]
The code uses only volume and mass, so density is not stored, nor updated in the particle. Density is used only to initialise the mass of the particle at the start of the step.
