### ISSUE TITLE
Velocity constraint on non-Cartesian elements

### ISSUE THREAD

**Issue by ezrayst** [cb-geo/mpm#207]
Current implementation applies velocity constraints at the nodes. Input includes `node id`, `direction = 0, 1 2` and `prescribed velocity`. This does not work for non uniform mesh.

Proposed summary of changes:
- Input would be `cell id`, `planeid`, `direction` in respect to the normal of face and `prescribed velocity` with positive being into the element
- `plane id` would be added to each element which contains 6 planes for hexahedron and 4 planes for quadrilateral, each with 1 dimension less than the dimension of the element. For instance, plane 0 of hexahedron consist of the plane made of nodes 0, 1, 4 and 5. 
- Currently, velocity constraint is stored in `nodes` but this `cell velocity constraint` will be in `mesh`
- It is applied during the mapping back from `nodes` to `particles`. So the application of velocity constraint depends on which element a particle belongs to
- During application, there will be rotation of the current velocity and acceleration to the constraint, and rotate back to the cartesian

**Comment by ezrayst** [comment]
List of tasks:
- [x] add plane id to elements hexahedron and quadrilateral
- [x] add private variable in `cell` for velocity constraint
- [x] change `read_mesh` and `mesh` to assign constraint to `cell`
- [ ] remove application of velocity constraint in `particle` 'compute_acceleration_velocity`
- [ ] in `particle`, update `compute_updated_position` to have rotation of velocity constraint before update position, velocity and acceleration from `cell`

**Comment by kks32** [comment]
Prescribed velocity should be positive, if it is in the direction of the normal and negative otherwise

**Comment by kks32** [comment]
Could you expand on how you the velocity constraints in the cell would be stored?

**Comment by kks32** [comment]
Cell constraints should be in the cell, not in the mesh.

**Comment by kks32** [comment]
This should not be changed "remove application of velocity constraint in particle 'compute_acceleration_velocity`" and it is applied on the nodes, not on the particle. In `compute_updated_position` in particle, a different function should be called, when cell has a constraint

**Comment by kks32** [comment]
Please ensure the list of tasks listed are also in the proposed changes. Not to copy, but to see if some of them have to be included in the proposed changes.

**Comment by kks32** [comment]
Fixed in #408
