### ISSUE TITLE
Overload shapefn, gradient and Bmatrix for particle size and deformation gradient

### ISSUE THREAD

**Issue by kks32** [cb-geo/mpm#236]
To support GIMP and CPDI it is important to include particle size and deformation gradient when calculating the shape functions. These shape functions are calculated at the particle level and are stored at the particles. In the particle `compute_shapefn()`, add a check to see if it is GIMP or CPDI before calculating the correct shape functions.

**Comment by kks32** [comment]
@cw646 I will do this, but watch this space.

**Comment by cw646** [comment]
Thanks! I like this way of detecting GIMP!
