### ISSUE TITLE
Mesh geometry as VTU

### ISSUE THREAD

**Issue by kks32** [cb-geo/mpm#263]
**Describe the feature**
Create mesh geometry as VTU to be rendered in paraview. VTU supports unstructured grid. 

**Describe alternatives**

**Additional context**
Allows for seeing cell crossing and number of particles in cell easily. 
3D Shapes: https://www.vtk.org/Wiki/VTK/Examples/Cxx/GeometricObjects/Cell3DDemonstration
https://lorensen.github.io/VTKExamples/site/Cxx/IO/WriteVTU/

**Comment by cbgeo** [comment]
Create VTK files from GMSH instead.
