### ISSUE TITLE
Cell needs particle size and deformation gradient to calculate the centroidal strain

### ISSUE THREAD

**Issue by cw646** [cb-geo/mpm#281]
GIMP shapefns require particle size and deformation gradient for calculating strain at the centroid of the cell. The call should be handled differently for GIMP and normal MPM. Since this is the centroid of the cell, GIMP neighbouring nodes will never be activated, hence, we can use Eigen::Matrix::Zero as size and deformation gradient.

**Comment by kks32** [comment]
Fixed in #285
