### ISSUE TITLE
Initial Stresses not set with Newtonian model

### ISSUE THREAD

**Issue by cw646** [cb-geo/mpm#344]
**Describe the bug**

When initial stresses are set using `initial-stresses.txt`, they will not be incorporated into the model when using either Bingham or Newtonian Materials.

When 
```
this->stress_.col(phase) =
          material_->compute_stress(this->stress_.col(phase), dstrain, this);
```
is called in the particle, the `stress` does contain the correct initial values, however, the material models do not draw from `stress`, they use `dstrain` to calculate `volumetric_strain` and `pressure`. Because dstrain will have 0 values in the initial time-step (as it is calculated after stress) the correct stresses are overwritten when `pressure` is used to calculate `pstress` (which is the returned value).

This is unlike ILE material which uses `stress += dstress` so the same error does not occur.

**To Reproduce**
Run a case with Newtonian material and an initial stress set using `initial-stresses.txt`.

**Expected behavior**
Even with initial stresses set, the model will start stresses from 0.

**Comment by kks32** [comment]
Closing as this is the behaviour of the material model.
