### ISSUE TITLE
Two-phase explicit algorithm

### ISSUE THREAD

**Issue by kks32** [cb-geo/mpm#351]

**Comment by srhgk2** [comment]
Following are the steps for two phase mpm explicit algorithm. I have attached a file expanding only a few steps and please work out the remaining steps.
1. Map particle solid, water and mixture masses to grid nodes
2. Map particle solid and water momentum to grid nodes
3. Compute nodal initial velocity fields
4. Assign nodal internal forces (for mixture and water phase)
5. Assign nodal body and traction forces (for mixture and water phase)
6. Assign nodal drag forces (for water phase only)
7. Compute acceleration of water phase
8. Compute acceleration of solid phase
9. Compute pore pressure
10. Update particle stress
11. Update particle velocities and position
12. Update particle porosity
13. Update particle volume and water mass
[twophase-explicit-mpm.pdf](https://github.com/cb-geo/mpm/files/2776846/twophase-explicit-mpm.pdf)

**Comment by kks32** [comment]
#370 supersedes this request
