### ISSUE TITLE
Add a history variable to particle class

### ISSUE THREAD

**Issue by thiagordonho** [cb-geo/mpm#352]
**Describe the feature**
In addition to the current stress and dstrain, certain constitutive models require additional parameters, which are stored in the material points (particle class). In the `compute_stress` function, the particle object is passed as a const pointer, which provides access to the particle class variables, however, the values of these variables cannot be updated. 

Although this approach satisfies the need for most constitutive models, some advanced models such as CamClay or Mohr-Coulomb with softening requires additional history dependent variables, whose value have to be updated within the material class in the `compute_stress` function. To achieve this, we propose a to add a variable called `history_` to `particle.h` that will store all history dependent parameters for a given material. This `history_` variable can be passed as a pointer to the material class when updating the stresses. 

The `history_`  private variable is declared as a [RobinHood map](https://github.com/Tessil/robin-map)  in the particle class:
`tsl::map<std::string,double>> history_;`

Additionally, `history_` is passed as a pointer to the `compute_stress` function:
`Vector6d compute_stress(const Vector6d& stress, const Vector6d& dstrain, const ParticleBase<Tdim>& ptr, tsl::map<std::string,double>* history)`

**Describe alternatives**
One alternative is to declare these required parameters individually, in the Particle class with a get and a set function. However, this is not ideal because each constitutive model has a different governing set of parameters.

Another alternative is to declare the variable history as a vector, however the worst-case peformance is O(n), while that for a map is O(1). Where `n` is the size of the vector.

**Additional context**
This process avoids having to pass the particle object as a mutable pointer since only the history variables have to be updated.

**Comment by kks32** [comment]
History variable inside the mesh class can be accessed and modified as:
```
   // To get a history variable `x`
  std::cout << "State var x: " << (*state_vars).at("x") << std::endl;
  // To update the history variable `x`
  (*state_vars).at("x") += 1.0;
```
