### ISSUE TITLE
Add particle state_variable to HDF5

### ISSUE THREAD

**Issue by tianchiTJ** [cb-geo/mpm#374]
**Describe the feature**
To present more field variables other than "stress, strain and velocity", which are stored in the particle class, some something should be added to the code. 

**Describe alternatives**
Add new part to the function "particles_vector_data" in "mesh.tcc".

**Comment by tianchiTJ** [comment]
Also need to add new part to the "std::vector<std::string> vtk = {"velocities", "stresses", "strains"}" in "mpm_base.tcc"

**Comment by z149181511** [comment]
For "resume" computation, the particle state_variable also need to be added to the functions :"write_particles_hdf5" and "read_particles_hdf5" in "mesh.tcc". In addition, change the value of "NFIELDS'' in the above two functions.
