### ISSUE TITLE
A nodel mass bug in resume computation

### ISSUE THREAD

**Issue by tianchiTJ** [cb-geo/mpm#398]
**Describe the bug**
if the computation resume from a step in which there are some cells without any particle but they have particles in the initial, it will give out the error message "Nodal mass is zero or below threshold". At the same time, it can still continue to run and output correct result.

**To Reproduce**
1. Compute a case and stop it after some steps, in which there are some cells transferring from  having-particles type to non-particle type
2. Run the resume computation from the stop step
3. See error: "Nodal mass is zero or below threshold"

**Expected behavior**
Refresh the list of cells activated.

**Comment by ezrayst** [comment]
The problem arises from the double initialization of the `particles`. Even though the `particles` have the right `cell_id`, the `cell` does not have the right `particles`.

Proposed solution: in resume, remove each particle from the cell it belongs to.
