### ISSUE TITLE
Unable to locate particle within a cell

### ISSUE THREAD

**Issue by ezrayst** [cb-geo/mpm#399]
**Description**
There are cases when a particle should be within a cell, but the code does not capture it.

**Example**
The inclined landslide problem is forced to stop when a particle is deemed to be outside the mesh.
![image](https://user-images.githubusercontent.com/22064721/55604008-839b2c00-5722-11e9-855c-82e11f847ed0.png)

However, by visual inspection, it is determined that the particle should be within the mesh still.
![image](https://user-images.githubusercontent.com/22064721/55604079-dd9bf180-5722-11e9-9433-a952d5ac7d19.png)

A [unit test](https://github.com/ezrayst/mpm/blob/de93f540f46e58a433df2ac763e55b72dcb8d993/tests/cell_test.cc#L209) is done to prove it.

**Comment by ezrayst** [comment]
![image](https://user-images.githubusercontent.com/22064721/55604001-754d1000-5722-11e9-8151-600b7d080312.png)

**Comment by kks32** [comment]
```
from __future__ import division
from sympy import * 
x, y, u, v = symbols('x y u v')
a1, a2, a3, a4 = symbols('a1 a2 a3 a4')
b1, b2, b3, b4 = symbols('b1 b2 b3 b4')
init_printing()

eq1 = (4 * x - a1) - (a2 * u + a3 * v + a4 * u * v)
eq2 = (4 * y - b1) - (b2 * u + b3 * v + b4 * u * v)
sol_u, sol_v = solve([eq1, eq2], [u,v])
```
