### ISSUE TITLE
Learning document

### ISSUE THREAD

**Issue by xuhenry** [cb-geo/mpm#45]
Hi all,
    Is there any learning document on the MPM code? For example, the example files, how to running  and visual the results.
Thanks a lot!
Best regards,
Henry

**Comment by kks32** [comment]
Hi @xuhenry 

This version of the MPM code is still under development, you could expect to have a working explicit version by end of the month. There are documents for our previous MPM code, which however aren't publicly available. You can find the MPM documents here: https://cb-geo.gitbooks.io/mpm3d-doc/content/

**Comment by cbgeo** [comment]
You can see the user doc: https://cb-geo.github.io/mpm-doc/#/
