### ISSUE TITLE
Material property test for bool

### ISSUE THREAD

**Issue by ezrayst** [cb-geo/mpm#480]
Function `property` in `material.h` is only outputting `double` material properties.
It does not work when we have a `bool` material property such as `softening` in Mohr-Coulomb and what I am developing with bonded NorSand.

[Code Line](https://github.com/cb-geo/mpm/blob/164a6665a2b791f893e0e5492c44625acda36de7/include/material/material.h#L59)

Suggestion:
Overloading the function with `bool`?

**Comment by kks32** [comment]
You can't overload a function with the same argument.

**Comment by ezrayst** [comment]
Should we make two different functions then? For instance: `property_double` and `property_bool`?

**Comment by kks32** [comment]
Where is it being used? could you share a snippet of where this is called?

**Comment by ezrayst** [comment]
It is used in the test cases only. An example will be this one:

[Bond Model Boolean](https://github.com/ezrayst/mpm/blob/b035e2428654a9788caff082042a5b39b95137bf/tests/material/nor_sand_test.cc#L126)

**Comment by kks32** [comment]
If it's for testing, I don't want to add a new function. We could test it differently, by checking the stresses when we have / not have a bond defined. Closing this issue.

**Comment by kks32** [comment]
Let me see if I can rewrite this as a templatized return.
