### ISSUE TITLE
Clone particle material history from a neighbour

### ISSUE THREAD

**Issue by srhgk2** [cb-geo/mpm#564]
**Describe the feature**
When adding a new particle, the material history of the new particle is cloned from a given neighbour particle.

- [x]  Add a function in particle class to clone the material state variables from a given particle hdf5 data

**Comment by kks32** [comment]
Could we just pass the `state_variables_` from the neighbouring particle, instead of the entire HDF5 object?

**Comment by srhgk2** [comment]
Is this good? 
`bool mpm::Particle<Tdim>::clone_neighbour_material_state_vars(
    const mpm::dense_map& state_vars,
    const std::shared_ptr<mpm::Material<Tdim>>& material)`
