### ISSUE TITLE
Run Test in MPI

### ISSUE THREAD

**Issue by bodhinandach** [cb-geo/mpm#575]
I try to run the `mpmtest` in develop by the following command:`mpirun -np XX mpmtest`, and it returns me an error. Are you aware of this and can help me out? Many thanks!
![image](https://user-images.githubusercontent.com/37140224/75737036-b1cb1800-5cb3-11ea-927a-95ff5fca626b.png)
This is the CMake command that I ran:
```
cmake ..                        \
-DCMAKE_BUILD_TYPE=Release      \
-DCMAKE_CXX_COMPILER=g++        \
-DKAHIP_ROOT=/home/Program/KaHIP \
-DHALO_EXCHANGE=On              \
```

**Comment by kks32** [comment]
MPI tests are enabled only on certain unit test sections, to test mpi code, please run:
`mpirun -n 4 ./mpmtest [mpi]`

using the `mpi` block tests only the MPI sections in the unit test
