### ISSUE TITLE
Write stresses and strains as a tensor output

### ISSUE THREAD

**Issue by kks32** [cb-geo/mpm#582]
**Describe the feature**
Stresses and strains should include all components

**Describe alternatives**
VTK Array is a possibility, but I need more help in doing that as we can't have vector data with more than 3 components

**Additional context**
Stresses and strains only print normal components at the moment

**Comment by bodhinandach** [comment]
@kks32 What's your progress on the VTK Tensor? Are you gonna do it as Array or Tensor? Let me know if I can help you.

**Comment by kks32** [comment]
@bodhinandach Array doesn't work very well, so I'm going with Tensors. I need to write test cases.
