### ISSUE TITLE
The particle_traction define

### ISSUE THREAD

**Issue by fengzekang** [cb-geo/mpm#584]
Hello, developer,
The particle traction force, how to deal with it?( I know the gravity is the external force for the particle)
We should define this whether it is the solid or liquid phase?
Best regards

**Comment by kks32** [comment]
Hi @fengzekang 

Please post user questions to https://forum.cb-geo.com/c/mpm/ so it will benefit a wider community. Issues on GitHub are for code related bugs. 

Please refer to https://mpm.cb-geo.com/#/user/preprocess/input?id=loading for applying loading conditions

**Comment by fengzekang** [comment]
Hello， @kks32 
I have some problem about the fluid simulation. I want to post the question on the https://forum.cb-geo.com/c/mpm/ .But maybe there is an error on this site. 
![5](https://user-images.githubusercontent.com/38140045/80913383-c3de3b00-8d76-11ea-87ba-23b40bca107f.gif)
The above picture is that I use the newtonian fluid and set the parameters with bulk=2.18e9, mu=0.001 and dt=1e-5. The problem is that some particles flying away and then the whole system broke, I think this is the unstable calculation phenomenon， but I am not sure about the reason.
Did you have any idea or suggestion. By the way, when to use the "pressure smoothing" and what is its function?
Best regards.
