### ISSUE TITLE
Constitutive Laws Development and Optimization

### ISSUE THREAD

**Issue by bodhinandach** [cb-geo/mpm#587]
I am creating this thread to discuss what we can generalize and improve furthers from the Constitutive Laws. So far my concerns are to:
- generalize state-variables naming, e.g. between epds and pdstrain
- create a common material_utility where functions like: compute stress invariants, principle stresses,  rotation transformation, tensor operators, etc. are implemented there.

If you have any other suggestions, we can discuss it here too. Feel free to add/tag anyone interested.

**Comment by kks32** [comment]
We could use the `geometry` namespace for rotations? Maybe we have a separate `tensor` space for common Tensorial operations?

**Comment by bodhinandach** [comment]
Are those namespaces are available now? Static functions work too, I am not sure which is better.

**Comment by kks32** [comment]
Yes `geometry` is already available

**Comment by ezrayst** [comment]
Finished with #600, do we need more? Otherwise we can close the issue I guess

**Comment by kks32** [comment]
Thanks Ezra!

**Comment by bodhinandach** [comment]
Thanks, Ezra, further functions can be added in the future. But as for now, it is good.
