### ISSUE TITLE
HDF5 - statevars

### ISSUE THREAD

**Issue by ezrayst** [cb-geo/mpm#602]
**Describe the bug**
`statevars` are not inputted in order within the HDF5 output file.

**To Reproduce**
Run this [simulation](https://www.dropbox.com/sh/8oj4kdhk02996ju/AAAwYfDV-kLt7oIqiO935-Zva?dl=0) with NorSand model.

**Expected behavior**
Here is my report on the different order than expected:
- `svars_0` is supposed to be `M_theta` and it is correct
- `svars_1` is supposed to be `void_ratio` but it is stored in `svars_7`
- `svars_2` is supposed to be `e_image` but it is stored in `svars_8`
- `svars_3` is supposed to be `p_image` but it is stored in `svars_4`
- `svars_4` is supposed to be `p_cohesion` but it is stored in `svars_9`
- `svars_5` is supposed to be `p_dilation` but it is stored in `svars_10`
and so on

**Comment by kks32** [comment]
Are there any results in `svars_1`, `svars_2` and `svars_3`? or are they empty?

**Comment by ezrayst** [comment]
They are zeros
