### ISSUE TITLE
Initialize particles with HDF5

### ISSUE THREAD

**Issue by ezrayst** [cb-geo/mpm#604]
**Describe the feature**
Instead of initializing particles with stresses and volumes, can we do initialize particles with HDF5 file? This way we can initialize state variables too (without using `resume` function).

**Describe alternatives**
Alternative includes just adding input files with state variables. Or pass the necessary variables to materials when stresses are computed.

**Additional context**
For the dam project, the shear modulus is a function of current stress (to get Gmax) and current strain (to get the degradation curve). If we start MPM simulation after the end of the dynamic simulation (done in FLAC / FEM), we need to input the current strain too.

**Comment by kks32** [comment]
Could we do `resume` at step 0 and would this work?

**Comment by ezrayst** [comment]
It might work!
