### ISSUE TITLE
Generate Random Particles for Accurate Integration 

### ISSUE THREAD

**Issue by ezrayst** [cb-geo/mpm#609]
# Generate Random Particles and Accurate Integration MPM Scheme

## Design Detail
- Have a new particle generator (currently either from 'file` or at `gauss points`)
- This generates random particles within a cell, on which the weights will be computed separately to ensure accurate integration
- The weights will ensure accurate integration

## Implementation Detail
- Start with generate random particles first
- Then once that's done, we will compute the gauss weights

**Comment by ezrayst** [comment]
After discussion with @kks32, we will change this from `cell` (generate points function). 

The new input JSON file might look something like this with label `random`:
```
  "particles": [
    {
      "generator": {
        "check_duplicates": true,
        "cset_id": -1,
        "particle_type": "P2D",
        "material_id": 2,
        "pset_id": 2,
        "particles_per_cell": 20,
        "type": "random"
      }
  ]
```

**Comment by kks32** [comment]
Could we have separate issues for updating weights and random particle generations?

**Comment by ezrayst** [comment]
Understood, will start with random particle generations first

**Comment by ezrayst** [comment]
Continued in #615
