### ISSUE TITLE
Bbar Implementation

### ISSUE THREAD

**Issue by ezrayst** [cb-geo/mpm#611]
**Describe the feature**
Bbar to separate volumetric and deviatoric computations, prevent locking for problems like undrained total stress analysis.

If no one else wants to do it, I could do it. I have done something before but this is not updated to the current develop branch: https://github.com/ezrayst/mpm/tree/bbar

**Comment by kks32** [comment]
I think the issue was how do we switch between doing bbar and not doing bbar without having to execute an `if` condition in every loop

**Comment by ezrayst** [comment]
Would another class that contains `compute_strain_rate` from velocity be helpful in this case? We might in the future implement enhanced strain or mixed method which would require some modifications to B matrix. So instead of `if` statements, we have a class maybe called `B-strain` or something

**Comment by kks32** [comment]
@ezrayst Could you share an implementation detail of how this might work, I don't understand how a separate class for `compute_strain_rate` would work.
