### ISSUE TITLE
Throw or not throw when particles are not found within mesh

### ISSUE THREAD

**Issue by ezrayst** [cb-geo/mpm#623]
**Describe the bug**
Within `mpm_explitic.tcc` when particles are not found within the current mesh, we throw according to this [line](https://github.com/cb-geo/mpm/blob/20bba5b1ebd2131ffbea674054c5c60aa5da8d1a/include/solvers/mpm_explicit.tcc#L275)

However, we then try to remove the particles in the next line. So is the code trying to remove the unlocatable particles or stop simulation when particles are lost? These few lines of codes are confusing.

**Expected behavior**
Since we are using an if statement already, maybe it's good to flag whether a user wants to remove or continue with unlocatable particles even though mass is not not conserved.

**Comment by bodhinandach** [comment]
@ezrayst I guess we already have the boolean: `this->locate_particles_` to remove the particles which cannot be located automatically. Did you mean that we need the removing option based on a particular criterion? If `this->locate_particles_` set `false`, it will automatically remove the particle when the search unable to find them.

**Comment by ezrayst** [comment]
Yeah, sorry, was looking at the wrong file. My bad!

**Comment by kks32** [comment]
Please see: 
https://mpm.cb-geo.com/#/user/preprocess/input?id=locate-particles-optional 

In JSON analysis section you can specify:     `"locate_particles": false,`
