### ISSUE TITLE
Error in computing the particle natural size

### ISSUE THREAD

**Issue by WeijianLiang** [cb-geo/mpm#641]
**Describe the bug**
Error in computing the particle natural size. The dimension doesn't match, eg. _unit_element_length_ is one-dimensional property, _cell_->nparticles_ is _Tdim_ dimensional property.  while the natural size should be dimensionless property.

This quantity doesn't affect any computation for standard MPM, but would significantly affect GIMP (make the support domain smaller, and its performance like standard MPM)

**Bug source**
__node.tcc__ (line 449 -450)
``      this->natural_size_.fill(element->unit_element_length() / ``
``                               cell_->nparticles());``

**Expected behavior**
``      this->natural_size_.fill(element->unit_element_length() / ``
``                       std::pow(cell_->nparticles(), static_cast<double>(1. / Tdim)));``

**Comment by ezrayst** [comment]
I think I agree with @WeijianLIANG. The definition of `nparticles` is the number of particles within the cell, while the length in GIMP is the length per dimension. What do you think @cw646?

**Comment by CwilkesQuad** [comment]
I think the listed reference alludes to the line "The initial size, 2l ip, is determined by dividing the cell spacing L by the number of particles per cell" from the paper. But the modification does make sense to me.

**Comment by cw646** [comment]
I think the listed reference alludes to the line "The initial size, 2l ip, is determined by dividing the cell spacing L by the number of particles per cell" from the paper. But the modification does make sense to me.

**Comment by kks32** [comment]
Fixed in #647
