### ISSUE TITLE
Error when running with parallel tasks

### ISSUE THREAD

**Issue by thiagordonho** [cb-geo/mpm#651]
**Describe the bug**
An error occurs when running a model with parallel tasks. The output states that `MPM main: Couldn't find key.MPM main`. Specifically, this error was firstly identified when submitting a job to run on multiple nodes on TACC's supercomputer: Stampede2.

**To Reproduce**
1. Compile with 
```
make -DBOOST_ROOT=$TACC_BOOST_DIR -DBOOST_INCLUDE_DIRS=$TACC_BOOST_INC -DCMAKE_BUILD_TYPE=Release -DEIGEN3_INCLUDE_DIR=$HOME/eigen -DKAHIP_ROOT=$HOME/KaHIP .. && make -j8
```
2. Run on 
```
ibrun $WORK/path/to/build/directory -f /path/to/file/ -i mpm.json
```
3. On condition: 2 nodes and 4 MPI tasks per node and using a `"nload_balance_steps"` smaller than the `"nsteps"`

**Expected behavior**
The simulation was expected to continue after the first multiple of `nload_balance_steps` is reached but it stops.

**Screenshots**
The following is a screenshot of the output after the error has ocurred:

![image](https://user-images.githubusercontent.com/42805669/84442999-5b4f6d00-ac04-11ea-9b12-209f708ee0e7.png)

**Runtime environment (please complete the following information):**
 - OS/Docker image: Unix
 - Branch: develop

**Additional context**
A detailed description for running on TACC is given [here](https://mpm.cb-geo.com/#/user/run/hpc/tacc-ls5).
A detailed description for running on your local machine with multiple tasks and MPI is given [here](https://github.com/cb-geo/mpm/blob/develop/README.md#compile-with-mpi-running-on-a-cluster).

**Comment by kks32** [comment]
The error happens in `robinhood::map` either we are missing a pointer to a particle or node. Needs further investigation.

**Comment by kks32** [comment]
I have narrowed this problem to `transfer_halo_particles` function call.
