### ISSUE TITLE
Easy way to do preprocess 

### ISSUE THREAD

**Issue by yy54787803** [cb-geo/mpm#733]
Hello, is there a easy way to do preprocess(generate the mesh and node from geometry model, add the boundary condition)

**Comment by kks32** [comment]
Hi @yy54787803 

We don't have a pre-preprocessor, but a project PyCbg supports MPM pre and post processing for easy python scripts for generating input files https://pypi.org/project/pycbg/

**Comment by yy54787803** [comment]
ok, thanks for your help
