### ISSUE TITLE
Use JSON to handle MPM input parameters

### ISSUE THREAD

**Issue by kks32** [cb-geo/mpm#75]
* Read input for MPM (mesh files and input parameters) from a JSON file

**Comment by ezrayst** [comment]
Proposal:
- `io.h` and `io.tcc` to handle all input and output
- Use of JSON to get the filename and other parameters such as gravity, spacing and friction
- Read input files and have pointers to nodes, element and material points -> then make them to `mesh` and `particles` class
- It should work like the `mpm-3d` code with a touchup using JSON file and using a separate class to handle IO

**Comment by kks32** [comment]
Handle only inputs, not outputs.
